# Site
name: 'ASPROS'
description: 'ASPROS, Yonsei University'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: ''
disqus: 'demowebsite'
email: 'asproslab@gmail.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
members:
  Hancheol-Cho:
    name: Hancheol Cho
    role: Professor
    site: https://www.wowthemes.net
    avatar: /assets/images/avatar1.jpg
    bio: "interesting about ~~~"
    email: hancho37@yonsei.ac.kr
    history:
     - " 연혁 "

  Jihyeok_Kim:
    name: Jihyeok Kim
    role: Master Course
    site: https://www.wowthemes.net
    avatar: /assets/images/avatar2.jpg
    bio: "test"
    email: wlgur7781@naver.com

    # Kyoeun-Kim:
    #   name:           Kyoeun Kim # 나타나는 이름
    #   site:           https://www.wowthemes.net
    #   avatar:         /assets/images/avatar1.jpg
    #   bio:            "Hi, I am Sal, the author of Mundana, the theme you're currently previewing. I hope you like it!"
    #   email:          kkyoeun28@yonsei.ac.kr

    # Seonghyun-Park:
    #   name:           Seonghyun Park
    #   site:           https://www.wowthemes.net
    #   avatar:         /assets/images/avatar2.jpg
    #   bio:            "Blogger, fashionista, love to explore new ideas and write on my morning coffee!"
    #   email:          ...@naver.com

    # Junseok-Moon:
    #   name:           Junseok Moon
    #   site:           https://www.wowthemes.net
    #   avatar:         /assets/images/avatar2.jpg
    #   bio:            "Blogger, fashionista, love to explore new ideas and write on my morning coffee!"
    #   email:          ...@naver.com
    

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]